List messageData = [
  {
    'text' : 'Hi!',
    'time' : '11:47 PM',
    'message_type' : 'text',
    'type' : 'sent',
    'status' : 'seen',
  },
  {
    'text' : 'How are you?!',
    'time' : '11:48 PM',
    'message_type' : 'text',
    'type' : 'sent',
    'status' : 'seen',
  },
  {
    'text' : 'Hello!',
    'message_type' : 'text',
    'time' : '11:48 PM',
    'type' : 'received',
    'status' : 'seen',
  },
  {
    'text' : 'I am good, What\'s about you?',
    'time' : '11:48 PM',
    'message_type' : 'text',
    'type' : 'received',
    'status' : 'unseen',
  },
  {
    'text' : 'This is test message from UI!',
    'message_type' : 'text',
    'time' : '11:49 PM',
    'type' : 'sent',
    'status' : 'seen',
  },
  {
    'text' : 'I know that 😎',
    'message_type' : 'text',
    'time' : '11:49 PM',
    'type' : 'received',
    'status' : 'unseen',
  },
  {
    'text' : '🤪',
    'message_type' : 'emoji',
    'time' : '11:49 PM',
    'type' : 'sent',
    'status' : 'unseen',
  },
];